language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

install:
  # upgrade gcc
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99

script:
  - mkdir build
  - cd build
  - cmake .. && make
